Game:	game 
game:	playGame.cpp AbstractHex.cpp AbstractHex.h HexAdapter.cpp HexAdapter.h HexArray1D.cpp HexArray1D.h HexVector.cpp HexVector.h Cell.cpp Cell.h
	g++ -std=c++11 -c playGame.cpp
	g++ -std=c++11 -c AbstractHex.cpp
	g++ -std=c++11 -c HexAdapter.cpp
	g++ -std=c++11 -c HexArray1D.cpp
	g++ -std=c++11 -c HexVector.cpp
	g++ -std=c++11 -c Cell.cpp
	g++ -std=c++11 -o playGame playGame.o AbstractHex.o HexAdapter.o HexArray1D.o HexVector.o Cell.o
	./playGame
